# CodeGrader - https://github.com/ooemperor/CodeGrader
# Copyright © 2023, 2024 Michael Kaiser <michael.kaiser@emplabs.ch>
#
# This file is part of CodeGrader.
#
# CodeGrader is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# CodeGrader is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with CodeGrader.  If not, see <http://www.gnu.org/licenses/>.

- name: Install CodeGrader Software Software Frontend
  hosts: all
  vars: 
    - distro: bookworm
    - line_lxc_subuid: root:100000:65536
    - line_lxc_subgid: root:100000:65536
    - line_lxc_default_1: lxc.idmap = u 0 100000 65536
    - line_lxc_default_2: lxc.idmap = g 0 100000 65536
    - DB_PASSWORD: DATABASEPASSWORD
  gather_facts: true
  become: true
  tasks:
  
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install CodeGrader required apt packages
      apt:
        name: 
          - libpython3-dev
          - libpq-dev 
          - pip 
          - git
        state: present
    
    - name: Recursively remove directory for python venvs
      ansible.builtin.file:
        path: /usr/lib/python3.11/EXTERNALLY-MANAGED
        state: absent
        force: true

    - name: Recursively remove directory /opt/CodeGrader
      ansible.builtin.file:
        path: /opt/CodeGrader
        state: absent

    - name: Clone the CodeGrader repository into /opt/CodeGrader
      ansible.builtin.git:
        repo: https://github.com/ooemperor/CodeGrader.git
        dest: /opt/CodeGrader
        clone: yes
    
    - name: Install CodeGrader Frontend requirements
      ansible.builtin.pip:
        requirements: /opt/CodeGrader/codeGrader/frontend/requirements.txt

    - name: Rename the setup Script
      shell: mv setup_frontend.py setup.py
      args:
        chdir: /opt/CodeGrader

    - name: Install the CodeGrader Application Frontend
      shell: pip install .
      args:
        chdir: /opt/CodeGrader
